Replace if by early return in pre-commit

diff --git a/git_template/hooks/pre-commit b/git_template/hooks/pre-commit
--- a/git_template/hooks/pre-commit
+++ b/git_template/hooks/pre-commit
@@ -6,39 +6,36 @@
 PROJECT=$(pwd)
 FILES=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php$`
 
-if [ "$FILES" != "" ]
+[ -z "$FILES" ] && exit 0
+
+echo "Checking PHP Lint..."
+
+for FILE in $FILES
+do
+  php -l -d display_errors=0 $PROJECT/$FILE
+  if [ $? != 0 ]
+  then
+      echo "Fix the error before commit."
+      exit 1
+  fi
+  FILES="$FILES $PROJECT/$FILE"
+done
+
+# Determine wether this project contains phpcs
+[ ! -f ./vendor/bin/phpcs ] && exit 0
+
+STANDARDS_FILE=""
+if [ -f ./vendor/grrr-amsterdam/garp3/phpcs.xml ]
 then
-    echo "Checking PHP Lint..."
-    for FILE in $FILES
-    do
-        php -l -d display_errors=0 $PROJECT/$FILE
-        if [ $? != 0 ]
-        then
-            echo "Fix the error before commit."
-            exit 1
-        fi
-        FILES="$FILES $PROJECT/$FILE"
-    done
+  STANDARDS_FILE="./vendor/grrr-amsterdam/garp3/phpcs.xml"
+fi
 
-    # Determine wether this project contains phpcs
-    if [ ! -f ./vendor/bin/phpcs ]
-    then
-        exit 0
-    fi
-
-    STANDARDS_FILE=""
-    if [ -f ./vendor/grrr-amsterdam/garp3/phpcs.xml ]
-    then
-        STANDARDS_FILE="./vendor/grrr-amsterdam/garp3/phpcs.xml"
-    fi
-
-    echo "Running Code Sniffer..."
-    ./vendor/bin/phpcs --standard=$STANDARDS_FILE --colors --encoding=utf-8 -n -p $FILES
-    if [ $? != 0 ]
-    then
-        echo "Fix the error before commit."
-        exit 1
-    fi
+echo "Running Code Sniffer..."
+./vendor/bin/phpcs --standard=$STANDARDS_FILE --colors --encoding=utf-8 -n -p $FILES
+if [ $? != 0 ]
+then
+  echo "Fix the error before commit."
+  exit 1
 fi
 
 exit $?
